### ISSUE TITLE
Publish to Packal

### ISSUE THREAD

**Issue by ngryman** [kbshl/alfred-vscode#1]
Hey, thanks for this extension! Would you mind publishing it to [packal.org](http://www.packal.org/) so we can find it and install it easily?

Thanks!

**Comment by kbshl** [comment]
Hey @ngryman, I've enabled the extension to be installed through `npm`. 

https://www.npmjs.com/package/alfred-vscode

Which IMHO is the better option. Therefore I will not publish it to packal, sorry.
